### ISSUE TITLE
Host docs on GitHub Pages, Netlify, or elsewhere

### ISSUE THREAD

**Issue by yudai-nkt** [OpenWonderLabs/SwitchBotAPI#6]
First of all, I appreciate all the hard work that has been put into this REST API. I can't wait to get my own API key.

IMHO, the current documentation is a bit hard to read because it's just a single lengthy README. I'd be happy if the documentation is split into a structured manner and deployed as a static web site.

I made a prototype of the documentation at https://switchbot-api-doc-prototype.netlify.app using [HonKit](https://github.com/honkit/honkit), an active fork of the abandoned [GitBook CLI](https://github.com/GitbookIO/gitbook-cli). I personally prefer MkDocs (written in Python) for its material theme and extensibility, but I choose HonKit for the following reasons:

- Python doesn't have an established dependency management compared to Node.js
- TypeScript projects are hosted under OpenWonderLabs organization, so developers here should be familiar with the npm ecosystem

Before submitting a PR, I'd like to ask for your feedback. Should a documentation site really be hosted? If so, what toolchain should be used?

**Comment by Minsheng** [comment]
Yudai Nakata様
This is Davidson from the dev team. The prototype looks awesome! I agree that the document should be published in a structured manner so that other developers can read with ease. HonKit looks pretty neat. MkDocs is easier to maintain.
To be honest, we currently don't have strong preferences over the particular toolchain to be used, but we do care about extensibility more. Anyhow, we don't have plans on moving the doc to a site yet but we will definitely improve the readability in the near future.
Cheers,
Davidson

**Comment by yudai-nkt** [comment]
Thank you for your opinion. I'll leave my fork and branch as is so that we can easily revisit this issue whenever you are ready in the future.

P.S. I finally received v5.0 update of my Android app a few days ago, and I've been toying around with the API. It's really exciting!
